### ISSUE TITLE
Install commands not working

### ISSUE THREAD

**Issue by Rhys-McAlister** [bowang-lab/Graph-Mamba#1]
Attempting to use the install commands in the readme and finding the below error:

Platform: WSL 

`conda clean --all
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - appdirs==1.4.4=pypi_0
  - argparse==1.4.0=pypi_0
  - asttokens==2.4.1=pypi_0
  - attrs==23.2.0=pypi_0
  - automat==22.10.0=pypi_0
  - axial-positional-embedding==0.2.1=pypi_0
  - buildtools==1.0.6=pypi_0
  - causal-conv1d==1.0.2=pypi_0
  - click==8.1.7=pypi_0
  - cmake==3.28.1=pypi_0
  - comm==0.2.1=pypi_0
  - constantly==23.10.4=pypi_0
  - cuda-cudart==11.7.99=0
  - cuda-cupti==11.7.101=0
  - cuda-libraries==11.7.1=0
  - cuda-nvrtc==11.7.99=0
  - cuda-nvtx==11.7.91=0
  - cuda-runtime==11.7.1=0
  - debugpy==1.8.0=pypi_0
  - decorator==5.1.1=pypi_0
  - docker-pycreds==0.4.0=pypi_0
  - docopt==0.6.2=pypi_0
  - einops==0.7.0=pypi_0
  - exceptiongroup==1.2.0=pypi_0
  - executing==2.0.1=pypi_0
  - ffmpeg==4.3=hf484d3e_0
  - fsspec==2023.12.2=pypi_0
  - furl==2.1.3=pypi_0
  - gitdb==4.0.11=pypi_0
  - gitpython==3.1.40=pypi_0
  - greenlet==3.0.3=pypi_0
  - huggingface-hub==0.20.1=pypi_0
  - hyperlink==21.0.0=pypi_0
  - importlib-metadata==7.0.1=pypi_0
  - incremental==22.10.0=pypi_0
  - ipykernel==6.28.0=pypi_0
  - ipython==8.18.1=pypi_0
  - jedi==0.19.1=pypi_0
  - joblib==1.3.2=pypi_0
  - jupyter-client==8.6.0=pypi_0
  - jupyter-core==5.7.0=pypi_0
  - libcublas==11.10.3.66=0
  - libcufft==10.7.2.124=h4fbf590_0
  - libcufile==1.8.1.2=0
  - libcurand==10.3.4.107=0
  - libcusolver==11.4.0.1=0
  - libcusparse==11.7.4.91=0
  - libnpp==11.7.4.75=0
  - libnvjpeg==11.8.0.2=0
  - lightning-utilities==0.10.0=pypi_0
  - lit==17.0.6=pypi_0
  - littleutils==0.2.2=pypi_0
  - local-attention==1.9.0=pypi_0
  - mamba-ssm==1.0.1=pypi_0
  - matplotlib-inline==0.1.6=pypi_0
  - nest-asyncio==1.5.8=pypi_0
  - ninja==1.11.1.1=pypi_0
  - ogb==1.3.6=pypi_0
  - orderedmultidict==1.0.1=pypi_0
  - outdated==0.2.2=pypi_0
  - packaging==23.2=pypi_0
  - pandas==2.1.4=pypi_0
  - parso==0.8.3=pypi_0
  - performer-pytorch==1.1.4=pypi_0
  - pexpect==4.9.0=pypi_0
  - platformdirs==4.1.0=pypi_0
  - prompt-toolkit==3.0.43=pypi_0
  - protobuf==4.25.1=pypi_0
  - psutil==5.9.7=pypi_0
  - ptyprocess==0.7.0=pypi_0
  - pure-eval==0.2.2=pypi_0
  - pyg-lib==0.3.1+pt20cu117=pypi_0
  - pygments==2.17.2=pypi_0
  - pyparsing==3.1.1=pypi_0
  - python-dateutil==2.8.2=pypi_0
  - pytorch==2.0.0=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda==11.7=h778d358_5
  - pytorch-mutex==1.0=cuda
  - pytz==2023.3.post1=pypi_0
  - pyyaml==6.0.1=pypi_0
  - pyzmq==25.1.2=pypi_0
  - rdkit==2023.9.3=pypi_0
  - redo==2.0.4=pypi_0
  - regex==2023.12.25=pypi_0
  - safetensors==0.4.1=pypi_0
  - scikit-learn==1.3.2=pypi_0
  - scipy==1.11.4=pypi_0
  - sentry-sdk==1.39.1=pypi_0
  - setproctitle==1.3.3=pypi_0
  - simplejson==3.19.2=pypi_0
  - six==1.16.0=pypi_0
  - smmap==5.0.1=pypi_0
  - sqlalchemy==2.0.25=pypi_0
  - stack-data==0.6.3=pypi_0
  - tensorboardx==2.6.2.2=pypi_0
  - threadpoolctl==3.2.0=pypi_0
  - tokenizers==0.15.0=pypi_0
  - torch-cluster==1.6.3+pt20cu117=pypi_0
  - torch-geometric==2.0.4=pypi_0
  - torch-scatter==2.1.2+pt20cu117=pypi_0
  - torch-sparse==0.6.18+pt20cu117=pypi_0
  - torch-spline-conv==1.2.2+pt20cu117=pypi_0
  - torchaudio==2.0.0=py39_cu117
  - torchmetrics==0.9.3=pypi_0
  - torchtriton==2.0.0=py39
  - torchvision==0.15.0=py39_cu117
  - tornado==6.4=pypi_0
  - tqdm==4.66.1=pypi_0
  - traitlets==5.14.1=pypi_0
  - transformers==4.36.2=pypi_0
  - twisted==23.10.0=pypi_0
  - tzdata==2023.4=pypi_0
  - wandb==0.16.1=pypi_0
  - wcwidth==0.2.12=pypi_0
  - yacs==0.1.8=pypi_0
  - zipp==3.17.0=pypi_0
  - zope-interface==6.1=pypi_0

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

EnvironmentNameNotFound: Could not find conda environment: graph-mamba
You can list all discoverable environments with `conda info --envs`.`

**Comment by ChloeXWang** [comment]
Hi Rhys, thank you so much for the using our tool and sharing the feedback! I will try to reproduce the error and loop back shortly.

**Comment by Rhys-McAlister** [comment]
> Hi Rhys, thank you so much for the using our tool and sharing the feedback! I will try to reproduce the error and loop back shortly.

Thanks!

**Comment by ChloeXWang** [comment]
Hi Rhys,

Thank you for your patience! Would you mind trying these commands instead to see if it works?
```
conda create -n graph-mamba python==3.9
conda activate graph-mamba
pip install torch==1.13.0
pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
pip install torch_geometric==2.0.4

pip install transformers==4.36.2
pip install torchmetrics==0.10.3
pip install openbabel-wheel
pip install fsspec 
pip install rdkit
pip install pytorch-lightning yacs
pip install performer-pytorch
pip install tensorboardX
pip install ogb
pip install wandb

pip install causal-conv1d==1.0.2
pip install mamba-ssm==1.0.1
```

The mamba installation (last two lines) might be a bit tricky. Please feel free to refer to the common issues such as cuda dependency in their repo https://github.com/state-spaces/mamba or we could look into it together.

**Comment by Rhys-McAlister** [comment]
Thank you for the response, you were correct those two last lines were tricky.

`Collecting causal-conv1d==1.0.2
  Using cached causal_conv1d-1.0.2.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /tmp/pip-install-_txvuxlg/causal-conv1d_6c9aaf7a6ea4488f91528d397f701b26/setup.py:78: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_txvuxlg/causal-conv1d_6c9aaf7a6ea4488f91528d397f701b26/setup.py", line 112, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined


      torch.__version__  = 1.13.0+cu117


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Collecting mamba-ssm==1.0.1
  Downloading mamba_ssm-1.0.1.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /tmp/pip-install-dy2v6xzo/mamba-ssm_45311b26096b450c9b61a4164acc8b62/setup.py:77: UserWarning: mamba_ssm was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dy2v6xzo/mamba-ssm_45311b26096b450c9b61a4164acc8b62/setup.py", line 111, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined


      torch.__version__  = 1.13.0+cu117


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Any help with this would be much appreciated. I have had a look through the steps in this repo originally but haven't had much success.

Thanks in advance

**Comment by ChloeXWang** [comment]
Gotcha, this [issue](https://github.com/state-spaces/mamba/issues/223) seems relevant. Could you type in `nvidia-smi` or `nvcc --version` in command line to check your cuda version?

**Comment by wendongj** [comment]
> Thank you for the response, you were correct those two last lines were tricky.
> 
> `Collecting causal-conv1d==1.0.2 Using cached causal_conv1d-1.0.2.tar.gz (6.4 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [13 lines of output] /tmp/pip-install-_txvuxlg/causal-conv1d_6c9aaf7a6ea4488f91528d397f701b26/setup.py:78: UserWarning: causal_conv1d was requested, but nvcc was not found. Are you sure your environment has nvcc available? If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc. warnings.warn( Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-install-_txvuxlg/causal-conv1d_6c9aaf7a6ea4488f91528d397f701b26/setup.py", line 112, in if bare_metal_version >= Version("11.8"): NameError: name 'bare_metal_version' is not defined
> 
> ```
>   torch.__version__  = 1.13.0+cu117
> 
> 
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. Collecting mamba-ssm==1.0.1 Downloading mamba_ssm-1.0.1.tar.gz (28 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [13 lines of output] /tmp/pip-install-dy2v6xzo/mamba-ssm_45311b26096b450c9b61a4164acc8b62/setup.py:77: UserWarning: mamba_ssm was requested, but nvcc was not found. Are you sure your environment has nvcc available? If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc. warnings.warn( Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-install-dy2v6xzo/mamba-ssm_45311b26096b450c9b61a4164acc8b62/setup.py", line 111, in if bare_metal_version >= Version("11.8"): NameError: name 'bare_metal_version' is not defined
> 
> ```
>   torch.__version__  = 1.13.0+cu117
> 
> 
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.`
> 
> Any help with this would be much appreciated. I have had a look through the steps in this repo originally but haven't had much success.
> 
> Thanks in advance

I have the same issue, and my system is ubuntu, when I type the command "nvcc -V", it shows no nvcc, so I install the cudatoolkit in my computer, after I install the cudatoolkit, then the "nvcc -V" is ok, then I set "CUDA_HOME=/usr/local/cuda-X.X", now I can install  mamba-ssm. I did not know if this is useful for your system

**Comment by williamnyren** [comment]
The most straightforward method I found for installing `nvcc` was to utilize the conda package within the environment. You can install it using the following command:
`conda install nvidia/label/cuda-11.7.1::cuda-nvcc`

There are also other versions available:
[https://anaconda.org/nvidia/cuda-nvcc](url)

**Comment by ChloeXWang** [comment]
Thank you for your comments!

**Comment by Andy-Yuaner** [comment]
"I noticed that the official GitHub versions currently provided are all based on CUDA 11.8, while the requirements file for this project specifies CUDA 11.7. Should I upgrade to CUDA 11.8, or are there alternative solutions? Thank you!
