### ISSUE TITLE
 Issue with Running ´peptides-func-EX.yaml´

### ISSUE THREAD

**Issue by williamnyren** [bowang-lab/Graph-Mamba#2]
Hello,

I encountered an issue when running the example provided on the page using the following command:

python main.py --cfg configs/Mamba/peptides-func-EX.yaml  wandb.use False

After the preprocessing phase was completed and just as the first training epoch was about to start, I received the following error:

```
Python

Traceback (most recent call last):
  File "/home/user/Documents/Graph-Mamba/main.py", line 175, in <module>
    train_dictcfg.train.mode)
  File "/home/user/Documents/Graph-Mamba/graphgps/logger.py", line 245, in write_epoch
    task_stats = self.classification_multilabel()
  File "/home/user/Documents/Graph-Mamba/graphgps/logger.py", line 146, in classification_multilabel
    'accuracy': reformat(acc(pred_score, true)),
  File "/home/user/Documents/Graph-Mamba/graphgps/metric_wrapper.py", line 323, in __call__
    return self.compute(preds, target)
  File "/home/user/Documents/Graph-Mamba/graphgps/metric_wrapper.py", line 311, in compute
    x = torch.stack(metric_val)  # PyTorch<=1.9
RuntimeError: stack expects a non-empty TensorList
```
For comparison, I also ran `mnist-EX.yaml` and `peptides-struct-EX.yaml`. Both of these scripts executed as expected without any issues. This leads me to believe that the issue is not related to my installation of the conda environment and all the packages.

Any guidance or assistance would be greatly appreciated.

Thank you.

**Comment by ChloeXWang** [comment]
Thank you for your feedback! I suspect it's with the `torchmetrics` version. Do you know which version you are using right now? Could you try installing `torchmetrics==0.9.3` and see if that works?
